const EVENTS = {
  GAME_START: 'GAME_START',
  GAME_OVER: 'GAME_OVER',
  GAME_RESTART: 'GAME_RESTART',

  GAME_INTRO_START: 'GAME_INTRO_START',
  GAME_INTRO_COMPLETE: 'GAME_INTRO_COMPLETE',

  PLAYER_ACTION: 'PLAYER_ACTION',

  HIGH_SCORE_RECORD: 'HIGH_SCORE_RECORD',
  HIGH_SCORE_RESET: 'HIGH_SCORE_RESET',
  ACHIEVEMENT: 'ACHIEVEMENT',
};

export default EVENTS;
